### ISSUE TITLE
加载扩展后，浏览器运行后报错

### ISSUE THREAD

**Issue by liamraycoder** [webman-tech/log-reader#1]
![image](https://user-images.githubusercontent.com/52949711/223964529-3b7ca085-860b-40ee-9ce4-fdb8c2fbf6b7.png)

**Comment by krissss** [comment]
更新一下依赖试下：
`composer require webman-tech/log-reader -W`

确保 `kriss/log-reader` 在 1.3.3 版本

**Comment by liamraycoder** [comment]
> 更新一下依赖试下： `composer require webman-tech/log-reader -W`
> 
> 确保 `kriss/log-reader` 在 1.3.3 版本

谢谢，更新了下依赖，已解决
